### ISSUE TITLE
Working with Strings

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#10]
_This assignment is due on Jan 29, 2015._
- Take a string from the user, reverse it, remove the last character and reverse it again (no shortcuts)
- Be sure if the user enters whitespace on either side of the input, that you remove it first
- For the original text input by the user, count how many words (as separated by spaces) and print this count.

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/blob/master/assignment_10.rb

**Comment by brianburridge** [comment]
:+1:
