### ISSUE TITLE
Asking Questions

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#12]
_This is assignment 12 and is due on Feb 02, 2015._
- Create an array of questions (Strings)
- Iterate over the array using each, asking each question to the user
- Bonus: Save all the answers with the questions, and print a summary at the end

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/blob/master/assignment_12.rb

**Comment by brianburridge** [comment]
@kjswartz The solution you have for 12, 15, and 17 are all severely limited to handle a certain number of questions. What we wants is code that could handle any number of questions. You as a developer, won't know how many someone else puts in the questions.txt or questions.json.

That's the great part about using Collections, we can iterate over them not caring how many objects are within them.

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/blob/master/assignment_12.rb

**Comment by brianburridge** [comment]
:+1:
