### ISSUE TITLE
A Guessing Game

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#13]
_This is assignment 13 and is due on Feb 02, 2015._
- Create a guessing game
- The user must guess the number chosen by the app
- Provide feedback to the user as to if their guess is lower or higher than the number
- Count the number of guesses and output at the end

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/blob/master/assignment_13.rb

**Comment by brianburridge** [comment]
:+1:
