### ISSUE TITLE
Read a screenplay and save it to a file

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#16]
_This is assignment 16 and is due on Feb 02, 2015._
- Pick a screenplay from this list, http://www.simplyscripts.com/ (in text)
- Read in the screenplay and write it to a local file

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/blob/master/assignment_16.rb

**Comment by brianburridge** [comment]
:+1:
