### ISSUE TITLE
Parsing JSON

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#17]
_This is assignment 17 and is due on Feb 03, 2015._
- Read about [HTTP](http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol)
- Read review on [using JSON in Ruby](https://hackhands.com/ruby-read-json-file-hash/)
- Look thru some [JSON Examples](http://json.org/example)
- Copy assignment 15 and modify to now read in questions from a JSON file
- This means you need to create a JSON file of you questions
- Read and parse the JSON into an array so the rest of the app remains the same

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/commit/5cb9208adf60834b7b3b0847edf0238770ff9c58

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/blob/master/Day%205/assignment_17.rb

**Comment by brianburridge** [comment]
:+1: 
The JSON could be a lot simpler, but I'll show that tomorrow in class.
