### ISSUE TITLE
Movie Querying script

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#18]
_This is assignment 18 and is due on Feb 04, 2015._
- http://developer.rottentomatoes.com/
- Use Rotten Tomato's movie querying script to create a command line app which prompts the user for a movie title
- Using the entered movie title, search via the API for the movie's synopsis and output to the user
- If more than one movie comes back, show all the movie title matches with their synopsis

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/blob/master/assignment_18.rb

**Comment by brianburridge** [comment]
Hey @kjswartz,

It's really hard for me to review this code because it's not indented properly. Can you do that and let me know when it's ready and I'll take another look? Thank you

**Comment by kjswartz** [comment]
uncluttered...https://github.com/kjswartz/Assignments/blob/master/assignment_18.rb

**Comment by brianburridge** [comment]
Soooo much better! :+1:
