### ISSUE TITLE
Attributes, accessors, instance variables and private methods

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#21]
_This is assignment 21 and is due on Feb 05, 2015._
- Write a Person class and some code to use it, following the directions below.
## First
- Create a Person class with attributes: first name, last name, and birthdate.
- First name and last name should not be able to be written to, but should be readable.
- Birthdate can be set and read.
- Create a public instance method called `name` that takes the name and sets the first name and last name instance variables. This is so the first name and last name attributes are set by passing in one name.
- Create a public instance method called `age` to calculate and return the user's age.
- Now, outside the Person class, ask the user their information and use it to create the Person object.
- After asking each user their information, output the user's age.
## Next
- Create a class variable that will count the number of people that enter in their information. After you output the person's age, also output the number of person they are so far (using the class variable).
- Loop to allow another user to enter their information. (exit when user enters \q for name). Create a Person object for each user.
- Create a private method called `calculateAge`. This should contain the functionality you previously had in the `age` method. The public `age` method should now call this new private `calculateAge` method.

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/blob/master/assignment_21.rb

**Comment by brianburridge** [comment]
Hi @kjswartz 

This works fine but the code could be improved in a few spots, particularly the variables being used for the calculate age.
1. The method to retriever the user's age should be `age`. So the output would look like: `person.age`
   And age therefore wouldn't take an argument and would be a getter not a setter.
2. The user's birthdate should be put into the birthdate attribute (using it's setter).
3. Then the calculateAge method would be called from the `age` method, and would use the _birthdate_ attribute.

Make sense?

**Comment by kjswartz** [comment]
Yes, makes sense now that I've been walked away from it for a bit. Cleaned up utilizing birthdate getter/setter functionality
