### ISSUE TITLE
Invoicing

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#23]
_This is assignment 23 and is due on Feb 09, 2015._
- Create an InvoiceItem class and an Invoice class (two classes in two separate files)
- The InvoiceItem class should have the following attributes: product_name, sale_price, quantity, tax percentage
- The invoice class should have a getter and setter for an attribute called: _items_ to hold an array of all the InvoiceItems
- Create an instance method in Invoice that will calculate a total of all it's invoice items
- Use reject or select methods in order to remove any InvoiceItem objects that have a zero quantity
- Create an instance method in Invoice to sum up the invoice items and get a total
- Ask the user to enter in the attributes for each invoice item, hitting ENTER on product name when done
- With each invoice item entered, create the object and add it to the collection of invoice items within a single Invoice object.
- Then output each line item.
- Show a sub-total without the tax, then a line item for the tax, then the total.
- Bonus: make the invoice look like a real world invoice in the terminal

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/tree/master/assignment_23

**Comment by brianburridge** [comment]
This works well and is mostly all correct. It's close enough for me to close, but I do want to point out that the Invoice attribute `items` was supposed to be an array of Item objects.

You are creating the invoice item objects between lines 14 and 26, but then you convert them to a Hash and add them to the array. Instead you should have done:

```
    invoice.items << invoice_item
```

Does that make sense?

**Comment by kjswartz** [comment]
took out hash and changed code to work with array of array versus array of hashes.
https://github.com/kjswartz/Assignments/tree/master/assignment_23
