### ISSUE TITLE
Hiring and Firing Employees

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#24]
_This is assignment 24 and is due on Feb 09, 2015._
- Take the Employee and Company classes, and create functionality to allow the company to hire and fire an employee.
- Create a Ruby app that will use those classes to do the following:
- prompt the user to enter information for the company.
- prompt the user to enter each employee. It will then "hire" each of them.
- show a list of employees, with ids, then ask the user if they would like to fire an employee by entering that id.
- fire the employee by id and show an updated list with that employee no longer in it.

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/tree/master/assignment_24

**Comment by brianburridge** [comment]
@kjswartz I see you are doing the same thing here that you did in #23 , using Hashes for the collection of objects instead of the object itself. For this one though I'd like to see you go back and correct it so I can be sure you understand the difference.

**Comment by kjswartz** [comment]
removed hash and changed code to work with iterating over array of arrays.

**Comment by brianburridge** [comment]
Suggestion: in your Company class, the hire and fire methods take an argument called _passed_text_. That will confuse developers because it looks like you are expecting text to get passed there, as opposed to an employee object.

Other than that, looks great. :+1:
