### ISSUE TITLE
More work with classes, getters and setters (in class, pairing)

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#26]
_This is assignment 25b and is due on Feb 10, 2015._
- Design and code a Blog and Post class.
- These classes should model a system where a user can create a blog, which will have posts.
- A Blog can have a name, a user_name, and the collection of posts
- A Post can have a name, a summary, the body of the post, the published date, and a word count.
- Since both a blog and a post MUST have a name, override the initializer so that when an object of either class is created, a name must be supplied.

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/tree/master/assignment_25b

**Comment by kjswartz** [comment]
user must now enter blog name and post name before continuing.

**Comment by brianburridge** [comment]
For this, what I'm looking for is to have the initializer accept name as an argument so that developer instantiating a Blog object has to pass a name. Same with Post. That's all I intended for "requiring" a name. You don't have to do the length checks.

**Comment by kjswartz** [comment]
adjusted.

**Comment by brianburridge** [comment]
:+1:
