### ISSUE TITLE
Movie Query app form - in class

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#33]
_This is assignment 32 and is due on Feb 17, 2015._
- Change your movie query app and add an HTML form to prompt the user for a movie title and submit to the controller/action you already have.
- You can still use the HTTP GET method in this case, because we want the old way of passing it in the request url to work.
- Use bootstrap to improve the look of the form.
- Refer to [Bootstrap form stylings](http://getbootstrap.com/css/#forms)
- Refer to [Rails form helpers](http://guides.rubyonrails.org/form_helpers.html)

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/tree/756d043a7bf432a83124b340b5d0270901ad2049/movie_query

**Comment by brianburridge** [comment]
Very nice :+1:
