### ISSUE TITLE
Validations and Associations

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#35]
_This is assignment 34 and is due on Feb 19, 2015._
- [Read Active Record Validations](http://guides.rubyonrails.org/active_record_validations.html)
- [Read Active Record Associations](http://guides.rubyonrails.org/association_basics.html)
- Continuing with your app from assignment 33, add a second model (use the migration generator) and use a _reference_ and _belongs_to/has_many_ relationship.
- Also add at least three validations between the two models.
- Test your model relationships in the rails console to be sure they work.

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/tree/master/assignment33_jobs

**Comment by brianburridge** [comment]
:+1:
