### ISSUE TITLE
Checkboxes for Many to Many

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#39]
_This is assignment 38 and is due on Feb 25, 2015._
- Note: This is a bonus assignment for those all caught up on homework.
- Using the app from 36 and 37, add checkboxes to a form for a many to many relationship.
- Review the [Railscast for this topic](http://railscasts.com/episodes/17-habtm-checkboxes-revised)

**Comment by kjswartz** [comment]
Heroku: https://obscure-meadow-4016.herokuapp.com/
GitHub: https://github.com/kjswartz/Sport

Players can play for multiple teams. Checkboxes added to assign player to multiple teams.

**Comment by brianburridge** [comment]
:+1:
