### ISSUE TITLE
Adding a User model and scoping your app to the current user

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#40]
_This is assignment 39 and is due on Feb 26, 2015._
- Modify the app from assignment 36-38, to have a User model
- Also, modify any models that should be scoped to a User, to belong to a user object
- Only show the user's records when in that context
- Create a User guest record in the seed file
- Default your app to always use that User
- Modify at least one model's create to be automatically associated with that User when it's created.
- Deploy to Heroku
- Paste the link to your Heroku app in a comment here for my review

**Comment by kjswartz** [comment]
https://obscure-meadow-4016.herokuapp.com/users/302

**Comment by brianburridge** [comment]
:+1:
