### ISSUE TITLE
Using ActiveAdmin for fully customizable, but quick, back-end admins

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#41]
_This is assignment 40 and is due on Feb 26, 2015._
- Add [ActiveAdmin](https://github.com/activeadmin/activeadmin) to your current application
- Review the [documentation](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md)
- Create an active admin resource for every model in your app
- Do some customization
- Ensure all forms save and allow the user to set the relationships
- Deploy to Heroku
- Paste the link to your Heroku app in a comment here for my review

**Comment by kjswartz** [comment]
https://obscure-meadow-4016.herokuapp.com/

**Comment by brianburridge** [comment]
:+1:
