### ISSUE TITLE
Custom Rake Tasks

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#46]
_This is assignment 45 and is due on Mar 05, 2015._
- Read about [Rake tasks in Rails](http://guides.rubyonrails.org/command_line.html#rake)
- Create a custom rake task for your Pinterest app that will output the current count of all your models. Example:
  
  Teams: 4
  Users: 10
  Books: 15
  Authors: 2
  Movies: 1

**Comment by kjswartz** [comment]
https://github.com/kjswartz/pinterest
be rake db:counts

**Comment by brianburridge** [comment]
:+1:
