### ISSUE TITLE
Debugging a Rails Application

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#49]
_This is assignment 48 and is due on Mar 11, 2015._
- Read about ri [Up and Running With Ruby Interactive](http://samuelmullen.com/2012/01/up-and-running-with-ruby-interactive-ri/), [5 Reasons You Should Use ri To Read Ruby Documentation](http://www.jstorimer.com/blogs/workingwithcode/7766081-5-reasons-you-should-use-ri-to-read-ruby-documentation)
- Try [Dash](http://kapeli.com/dash)
- Try [OmniRef](https://www.omniref.com/)
- Sign up to use the [Suncoast Dev Slack](http://suncoast.io)
- Install the [better_errors gem](https://github.com/charliesome/better_errors) in your Pinterest application. Create an error to see how it works.
- Read about the [Rails logger](http://guides.rubyonrails.org/debugging_rails_applications.html) and implement some lines in your controller. Output an instance variable using the `.inspect` method to the log. Paste the section of your log file in a comment in this issue. In an issue comment direct me to where you have added the logger statements. (Yes, in this case you can check logger statements in).
- Read about using the [pry console debugger](https://github.com/nixme/pry-debugger) and try it in a controller action.

**Comment by kjswartz** [comment]
Placed loggers in the Pins controller, under the create method. 
https://github.com/kjswartz/pinterest

 User Load (0.4ms)  SELECT  "users".\* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "guest@guest.com"]]

I'm Here
Pin id: nil, board_id: 173, title: "Pebble", description: "many stones", url: "", image: nil, created_at: nil, updated_at: nil

   (0.4ms)  BEGIN

**Comment by brianburridge** [comment]
:+1:
