### ISSUE TITLE
Using SASS

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#53]
_This is assignment 52 and is due on Mar 17, 2015._
- [x] Read the [Asset Pipeline Rails guide](http://guides.rubyonrails.org/asset_pipeline.html)
- [x] Read through the [SASS Basics guide](http://sass-lang.com/guide)
- [x] Use SASS in one of your past apps, and ensure you do the following:
- [x] Change your application.css to be a SASS file and to use `import` statement instead of the require tree.
- [x] Ensure your custom css is listed in your layout file below bootstrap, so they override any bootstrap files
- [x] Create and use at least one partial. Suggestion: place a few color variables in a `colors` partial
- [x] Ensure the scaffold.css from the Rails scaffold generator is no longer in use
- [x] Use the `darken` function to have one color be auto darkened off of another.
- [x] Set your site's background color via a variable
- [x] Use a few "nested" styles
- [x] Setup [bourbon](http://bourbon.io/) in your app
- [x] Look through bourbon's mixins and use at least one in your app. Find them in the [documentation](http://bourbon.io/docs/)
- [x] Link to the repository for the app where you made these changes
- [x] Also link to the Heroku app where the changes are visible. Be sure to let me know which page to look at on the app if not the home page.

**Comment by kjswartz** [comment]
https://github.com/kjswartz/pinterest
https://secure-mountain-7773.herokuapp.com/

Styling is a bit messy, but I've already gone so far down the rabbit hole of bad choices I would have to wipe everything out and start again. Lesson learned for future projects to keep css/scss neat and concise utilizing SASS and css layouts. Things can become tangled very quickly when trying to go back through and retrofit. Reworking the styling from scratch is on my 'free time' list of things to do.

**Comment by brianburridge** [comment]
Everything is done except the one item I unchecked. You have your custom css above the bootstrap, but that allows bootstrap to override your personal decisions. It's safer to have you custom css below any framework css you import, so that you can override it successfully.

**Comment by brianburridge** [comment]
:+1:
