### ISSUE TITLE
Rails Native Authentication

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#54]
_This is assignment 53 and is due on Mar 18, 2015._
- Review [using cookies in Rails](http://api.rubyonrails.org/classes/ActionDispatch/Cookies.html)
- Review [Rails sessions](http://guides.rubyonrails.org/action_controller_overview.html#session)
- Review [has_secure_password](http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html)
- Add real user authentication to your Pinterest app
- User sign up, sign in, sign out
- Adjust current_user method in application controller to use the signed in user from the session

**Comment by kjswartz** [comment]
https://github.com/kjswartz/pinterest
https://secure-mountain-7773.herokuapp.com/

**Comment by brianburridge** [comment]
Looks good!
