### ISSUE TITLE
Ruby Koans, First Half

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#55]
_This is assignment 54 and is due on Mar 19, 2015._
- Download the [RubyKoans](http://rubykoans.com/)
- Create a local git repo and a GitHub repo for them
- Complete 1 - 141 of the Koans
- Check in your work and push to GitHub
- Please provide a link to your new GitHub repo for the Koans

**Comment by kjswartz** [comment]
216 of 282 completed
https://github.com/kjswartz/koans

**Comment by brianburridge** [comment]
:+1:
