### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#56]
_This is assignment 56 and is due on Mar 23, 2015._
- Review the [Rails testing guide](http://guides.rubyonrails.org/testing.html)
- Using your Pinterest app and conventional built in testing (note: you can load the testing db using any preferred means).
- Write some unit tests to check that all the models will not save unless they have valid data (testing the validations).
- Write a functional test to ensure the home page comes up with the proper data on it.
- Write a functional test to ensure clicking on a pin link display the correct view.
- Write a functional test to ensure the search works correctly.
- Write an integration test to ensure there is a nav providing links to the home page, the user's pins, and the user's boards
- Write an integration test to ensure only admins can get to the admin section.
- Write an integration test to ensure users can only see their own pins and only when they are logged in.

**Comment by kjswartz** [comment]
https://github.com/kjswartz/pinterest

**Comment by brianburridge** [comment]
@kjswartz when I run `rake` to run your test suite for this app, I get 3 failures and 8 errors.

Perhaps some of the tests were from the scaffold generator and need to be modified? Were you running the tests with `rake` or were you running specific tests?

**Comment by kjswartz** [comment]
Yes, I was running specific rake tests on the models, welcome controller, pins controller, and users_flow integration. Should I comment out the others?

**Comment by brianburridge** [comment]
Just delete the others.

**Comment by kjswartz** [comment]
adjusted.

**Comment by brianburridge** [comment]
:+1:
