### ISSUE TITLE
Sending Email

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#57]
_This is assignment 55 and is due on Mar 24, 2015._
- Read the Rails guide on [Action Mailer](http://guides.rubyonrails.org/action_mailer_basics.html)
- Add a welcome mailer to the sign up process in your Pinterest app
- Get it working on your laptop first, using the [letter_opener gem](https://github.com/ryanb/letter_opener)
  https://devcenter.heroku.com/articles/sendgrid#ruby-rails
- Next, deploy to Heroku and setup with sendgrid
- Ensure emails are being received by users when signing up on Heroku

**Comment by kjswartz** [comment]
https://github.com/kjswartz/pinterest
https://secure-mountain-7773.herokuapp.com/

Emails are being sent according to the heroku logs but I have yet to receive one and my reputation is now at 0%

**Comment by brianburridge** [comment]
I haven't received the email either. Let's look at it together.

**Comment by kjswartz** [comment]
At local market now. I checked the send grid dash/stats and it said they
were blocked due to being considered spam. I tweaked the message and
committed this morning and I was able to squeeze one through yahoo and get
the reputation back to 100%.

**Comment by brianburridge** [comment]
I checked my spam folder and found it! Could be they think you are impersonating Pinterest, which you are. Lol. That's probably all it is. :)

:+1:

**Comment by kjswartz** [comment]
Lol yeah they straight blocked it when I had pinterest@pinterest.com.
