### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#60]
_This is assignment 59 and is due on Mar 26, 2015._
- Add a [jQuery plugin](http://plugins.jquery.com/) to your Pinterest app
- Be sure to direct me to where on your app you've added it, both in your code and what page it's running on at Heroku so I can see it work.

**Comment by kjswartz** [comment]
I added a chosen search selector for pins board selector, when setting a pins board. On Heroku, visit a pins show page and either edit the pin, if you are the owner, or click the 'Pin It' button to add the pin and you will see the new chosen select box.

https://github.com/kjswartz/pinterest
https://secure-mountain-7773.herokuapp.com/

https://gist.github.com/kjswartz/e6f62165569c345273b5
app/assets/javascript/pins.coffee
app/views/pins/_form.html.erb

**Comment by brianburridge** [comment]
:+1:
