### ISSUE TITLE
CoffeeScript

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#61]
_This is assignment 60 and is due on Mar 30, 2015._
- Review the Rails guide on [Working with JavaScript in Rails](http://guides.rubyonrails.org/working_with_javascript_in_rails.html)
- Refer to the [CoffeeScript docs](http://coffeescript.org/)
- Write some CoffeeScript in your Pinterest app to listen for a click on the header/logo of your app (in the nav), and when clicked, popup a bootstrap modal with some about information for your app.
- Bonus: Use Ajax in one place in your Pinterest app (deleting an item, adding an item, etc)

**Comment by kjswartz** [comment]
@brianburridge: all the examples I am seeing are just calling on the modal right in the bootstrap code. I dont understand how to incorporate coffescript here? The searches I'm seeing are very confusing and I dont understand how coffescript comes into play here. 
https://gist.github.com/kjswartz/ef5e57bd30e7c14aaf0f

**Comment by kjswartz** [comment]
https://secure-mountain-7773.herokuapp.com/
https://gist.github.com/kjswartz/11f7f2defc36ca210f34
added about modal popup to navbar, which activates via coffee script.

**Comment by brianburridge** [comment]
:+1:
