### ISSUE TITLE
Creating Variables and Literals

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#7]
_This assignment is due on Jan 28, 2015._
- Create code for each comment in [this gist](https://gist.github.com/brianburridge/79de494772daf7976ea9)
- Run the code and paste the output into your issue as a comment for this assignment
- It should list all the proper class names and all class tests should result in 'true'
- Before you run it, can you guess what will happen with the constant code you've created?

**Comment by kjswartz** [comment]
kyles-mba:TheIronYard kyleswartz$ ruby gistfile1.rb 
String
Date
Fixnum
Array
Array
Hash
true
true
true
true
true
true
String
Fixnum
Array
Hash
Symbol
gistfile1.rb:42: warning: already initialized constant NAME
gistfile1.rb:40: warning: previous definition of NAME was here
Your new constant is toto
