### ISSUE TITLE
Working with Loops

### ISSUE THREAD

**Issue by brianburridge** [kjswartz/Assignments#8]
_This assignment is due on Jan 29, 2015._
- Request input of a number from the user.
- Iterate the number of times indicated by the input number
- Within the loop, print the number of the iteration
- Do this for each of these methods of looping: while, for i in rage, loop, until, .times with counter, until, range
- All should print from 1 to the number input by the user

**Comment by kjswartz** [comment]
https://github.com/kjswartz/Assignments/blob/master/assignment_8.rb

**Comment by brianburridge** [comment]
:+1:
